version: '2'

services:
  vms-gateway:
    build:
      context: .
      dockerfile: ./web.Dockerfile
      args:
        env: 'docker'
    image: vapormicroservice-gateway
    ports:
      - "9000:80"
